version: '3'
services:
#  app:
#    image: test-graphql
#    ports:
#      - "8080:8080"
#    depends_on:
#      - databases
  databases:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=toor